# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dbdocs
        run: sudo npm install -g dbdocs

      - name: Check dbdocs
        run: dbdocs

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          DBDOCS_TOKEN = ${{ secrets.DBDOCS_TOKEN }}
          dbdocs build ./noob.dbml --project=${{ secrets.DBDOCS_PROJECT }} --password=${{ secrets.PROJECT_PASSWORD }}
